### PR TITLE
Return one Autoloader per namespace

### PR DESCRIPTION
**Pull request by BrianHenryIE**
When a composer.json's autoload key contains two namespaces, return two Autoloader objects. e.g. RubixML/Tensor

https://github.com/RubixML/Tensor/blob/86bb628781f311684a6778744a22b283efdae58f/composer.json#L36-L39

### CODE REVIEW

**Comment by coenjacobs** [comment]
@BrianHenryIE Can I help you proceed with this PR? Is it ready to review yet or do you need anything?

**Comment by BrianHenryIE** [comment]
It's definitely not ready, TBH I never even ran the unit tests. The main point in the draft PR was to share the identified problem. 

I just personally encountered the un-prefixed classes ([#64](https://github.com/coenjacobs/mozart/issues/64#issuecomment-687444315), [#58](https://github.com/coenjacobs/mozart/issues/58#issuecomment-661737362)) so I'll be taking a look at that soon and I think as I fix it it might make sense to polish this PR too.

**Comment by BrianHenryIE** [comment]
This is pretty much ready to merge. I expect after the other PRs are merged, this will need master merged again first.

It changes Autoloaders from using a constructor to using a static method which will return an array of Autoloaders so both will be returned in the example:

```
"autoload": {
        "psr-4": {
            "Tensor\\": "src/",
            "JAMA\\": "lib/JAMA"
        }
    },
```

I wrote tests for `Composer/Package.php` (although only one was a failing test for this PR).

**Comment by BrianHenryIE** [comment]
I removed [getSearchNamespace()](https://github.com/coenjacobs/mozart/blob/3b1243ca8505fa6436569800dc34269178930f39/src/Composer/Autoload/Classmap.php#L27-L35) from `Composer/Autoload/Classmap.php` and from the `Autoloader` interface because it seems it's already more appropriately part of `NamespaceAutoloader` abstract class (which implements `Autoloader`).

That's what the Psalm warning is about. TBH, I only ran Psalm on the files that have been changed. As I said above, I expect to have to merge master in again before before this gets merged itself, and I know there are Psalm fixes already written that will conflict / waste effort if I were to write them here.

**Comment by darthvader666uk** [comment]
Thought I will give up an Update.

Been testing my code with this pull (via the issues that was raised: https://github.com/coenjacobs/mozart/issues/62?_pjax=%23js-repo-pjax-container) and so far so good.  AWS is doing what I want it to do (though It wont do it in the vendor folder directly, it needs to be done outside of it).

Will keep you posted and update more findings but so far, so good

**Pull request closed without merging**
