### PR TITLE
Fix all PHPStan Level 4 problems

### PR DESCRIPTION
**Pull request by szepeviktor**
```
 ------ ---------------------------------------------------------------------------------------------
  Line   Mover.php
 ------ ---------------------------------------------------------------------------------------------
  73     Access to an undefined property CoenJacobs\Mozart\Composer\Autoload\Autoloader::$namespace.
 ------ ---------------------------------------------------------------------------------------------

 ------ ---------------------------------------------------------------------------------------------------
  Line   Replace/NamespaceReplacer.php
 ------ ---------------------------------------------------------------------------------------------------
  22     Call to an undefined method CoenJacobs\Mozart\Composer\Autoload\Autoloader::getSearchNamespace().
 ------ ---------------------------------------------------------------------------------------------------
```

These interface-things are the 2 remaining ones.
Please use @phpstan.

### CODE REVIEW

**Comment by szepeviktor** [comment]
💡 The fun begins on Level 5+

**Comment by coenjacobs** [comment]
Thank you @szepeviktor, I have merged this with the latest `master` branch as I have today introduced Psalm (via #112) in our CI chain. This is merely a personal preference, as I think PHPStan and Psalm basically come down to the same principle.

As it turns out, Psalm found an issue with one of your changes and I don't know why the tests are failing. Will have to investigate a little bit. Might have to do with the fact that Psalm already changed some parts of the code that you also did and the changes might not add up any longer. Will have a look soon, but if you can have a look and update based on my merge commit, please let me know.

**Comment by szepeviktor** [comment]
Okay. I leave it up to you as Psalm has an unsustainable origin and I dug deep into PHPStan so I don't and won't speak Psalmish.

**Comment by szepeviktor** [comment]
Actually I've spent hundreds of hours to advocate PHPStan...

**Comment by szepeviktor** [comment]
Regarding

> src/Composer/Autoload/NamespaceAutoloader.php#L29
> $this->paths with declared type 'array<array-key, string>' cannot be assigned type 'non-empty-array<array-key, array<array-key, mixed>|string>'

autoload can be many different thing https://getcomposer.org/doc/04-schema.md#autoload

**Comment by coenjacobs** [comment]
@szepeviktor Care to elaborate on this statement?
>Psalm has an unsustainable origin
I'm not saying that Psalm is perfect, it's just a tool to run static analysis. If there are any real issues with Psalm, that I'm obviously not aware of, I'm open to changing. But I need some more motivation on that, other than just your word. So some links on the topic, or an educated opinion are very much appreciated.

**Comment by szepeviktor** [comment]
- Psalm's originates from a chaotic environment https://medium.com/vimeo-engineering-blog/fixing-code-that-aint-broken-a99e05998c24
- PHPStan is well-designed from the ground up https://youtu.be/majpU-_ShB0?t=24
- I'm in contact with project authors, so I write extensions, request features, report bugs, and inspire
- XML configuration is not for humans

**Pull request closed without merging**
