### PR TITLE
Support dependency tree of packages

### LINKED ISSUE #1: Support dependency tree of packages
At this point, the dependencies of a package you want to bundle inside your WordPress plugin are not handled. So, you need to specify them all in your `composer.json`, or they will not be moved into your own namespace. In future releases, I want to add support for looping through the tree of dependencies for each package to bundle, to automate this process.

### PR DESCRIPTION
**Pull request by costasovo**
~~I've added an option`--with_dependencies`  for the compose command. When the command runs without the option it does nothing to sub-deps and it works same as current version.~~

When the command runs it process all installed sub-dependencies of a package (required and suggested) as if they were listed in mozart config. ([commit](https://github.com/coenjacobs/mozart/commit/ab0af7b21443a96ea74aafa85a8da34828279943))

After moving all dependencies it replaces sub-dependency namespaces or classnames within parent dependency package. ([commit](https://github.com/coenjacobs/mozart/commit/9ce5b142ca28afddada5bf8ffd7da9da31a5a757))

Closes #1

### CODE REVIEW

**Comment by coenjacobs** [comment]
Thanks a lot @costasovo, this looks amazing already. I’m going to put it through intensive testing this week and will get back to it then. One thing that stands out to me right away is that I’d rather have the dependency tree flag default to `true`, making it the default behavior. I can’t think of many use cases where I’d leave this off, but it’s nice to have an option to do so for debugging purposes.

**Comment by costasovo** [comment]
Good point about making it a default option. I will update the PR.

**Comment by costasovo** [comment]
I've added a commit which changes the option to `--skip_dependencies` and the compose command processes  sub-dependencies by default.

**Comment by costasovo** [comment]
I've found out that it was not a good idea to process all installed suggested dependencies automatically since there could be a situation when two packages share dependency (one as required and one as suggested) and then the suggested one will be always processed.
I've added a commit which changes that. Suggested deps now have to be mentioned in mozart config to be processed.

**Comment by coenjacobs** [comment]
Thanks again @costasovo for working on this. I've just pushed my own take on processing the dependency tree in #12. Could you have a look there? Now only I need a way to give you official props on the project, if we don't go ahead with merging this PR, because your code definitely got me going. 😄

**Comment by coenjacobs** [comment]
I have released my solution to this problem in [release 0.3.0](https://github.com/coenjacobs/mozart/releases/tag/0.3.0), where I've given you credits, @costasovo - thanks a lot again! 🎉

**Pull request closed without merging**
