### PR TITLE
Generate classmap

### PR DESCRIPTION
**Pull request by BrianHenryIE**
This PR adds creation of a classmap file from the ~~PSR-0~~ "classmap_directory" files managed by Mozart.

Defaults to none.

Configured in `composer.json` with

```
"classmap_output": {
  "filename": "src/autoload_classmap.php",
  "relative_path": "/src"
},
```

Then used in the plugin with:

```
$class_map_file = __DIR__ . '/autoload_classmap.php';
if ( file_exists( $class_map_file ) ) {

	$class_map = include $class_map_file;

	if ( is_array( $class_map ) ) {
		spl_autoload_register(
			function ( $classname ) use ( $class_map ) {

				if ( array_key_exists( $classname, $class_map ) && file_exists( $class_map[ $classname ] ) ) {
					require_once $class_map[ $classname ];
				}
			}
		);
	}
}
```

### CODE REVIEW

**Comment by coenjacobs** [comment]
@BrianHenryIE Isn't this creating a duplicate file from what is already stored in the default classmap autoloader that Composer generates? I recall that the default classmap autoloader also contains the prefixed classes.

**Comment by BrianHenryIE** [comment]
I'll fix this soon.

I don't use composer in my actual plugins, just in dev. Unfortunately, I don't have anything public on GitHub that's actually using the classmap but you can see the idea at [this project](https://github.com/brianhenryie/bh-wp-autologin-urls) – Mozart copies and prefixes packages into `src/vendor`, I use my own `autoloader.php` and then I zip up the whole `src` directory as the plugin. 

I mentioned my lack of understanding in [one of the issues](https://github.com/coenjacobs/mozart/issues/44#issuecomment-641618518), maybe you could add a couple of words/links in the README to explain things to novices. I think that could be valuable to many WordPress developers!

**Comment by coenjacobs** [comment]
@BrianHenryIE You know how much I appreciate all the good work you do for this project, right? For now, I'd like you to pause this particular functionality for a while. @markjaquith and I have been turning this whole idea upside down in #66 now. Even though we're not quite close to white smoke, I doubt that this current approach is going to survive eventually and I'd hate for you to spend much more time on this than you already have.

**Comment by BrianHenryIE** [comment]
Sure. Since I'm already using it (with composer-patches) there might be a few commits to keep it working for me.

But.. I'm still in the dark as to how you are including "classmap" files in your projects. You run `mozart compose`, the files get copied, the classnames prefixed, then what? Does the Composer autoloader in `vendor/autoload.php` know where they are and what they're called? What exactly is `composer dump-autoload` doing?

**Comment by BrianHenryIE** [comment]
I drastically simplified this. It uses Composer itself now to generate the classmap. Doesn't need any config in composer.json. Adds `vendor/bin/mozart dump-autoload`.

**Comment by BrianHenryIE** [comment]
This is using `ob_get_contents()` and should be using `ob_get_clean()`.

**Pull request closed without merging**
