### PR TITLE
Fix release script

### PR DESCRIPTION
**Pull request by szepeviktor**
@coenjacobs

### CODE REVIEW

**Comment by coenjacobs** [comment]
@szepeviktor Thanks - I thought of this being the easiest. But what happens when this runs, is that the downloaded `phar-composer.phar` file is added to the `mozart.phar` file. Is there a way around this, that you know of?

**Comment by szepeviktor** [comment]
Seems like there are no options 😿 

```
$ $ php phar-composer-1.2.0.phar build -h
Usage:
 build [project] [target]

Arguments:
 project               Path to project directory or composer.json (default: ".")
 target                Path to write phar output to (defaults to project name)

Options:
 --help (-h)           Display this help message
 --quiet (-q)          Do not output any message
 --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
 --version (-V)        Display this application version
 --ansi                Force ANSI output
 --no-ansi             Disable ANSI output
 --no-interaction (-n) Do not ask any interactive question
```

**Comment by szepeviktor** [comment]
Please consider `box` to build your PHAR file.

**Comment by szepeviktor** [comment]
If you ask who it was I'll deny it was me :)

**Pull request closed without merging**
