### PR TITLE
Exclude dev. deps from PHAR file

### PR DESCRIPTION
**Pull request by szepeviktor**
14 MB is huge!

### CODE REVIEW

**Comment by szepeviktor** [comment]
Docker already has it: https://github.com/coenjacobs/mozart/blob/master/Dockerfile#L10

**Comment by coenjacobs** [comment]
You are correct, I must have somehow missed this. Thank you!

**Comment by szepeviktor** [comment]
@coenjacobs Please consider using the PHAR version: https://github.com/clue/phar-composer/releases

**Comment by coenjacobs** [comment]
Hmmm, that actually kills the build script, given the PHAR generating package [is actually a development dependency](https://github.com/coenjacobs/mozart/pull/105/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R26) so I can't just release this as is. I'm gonna investigate using the PHAR file for it instead.

**Pull request merged**
